CREATE DATABASE banka_sistemi;
use banka_sistemi;

CREATE TABLE hesap (HESAP_NUMARASI int NOT NULL AUTO_INCREMENT, TC varchar(11) NOT NULL, AD_SOYAD varchar(100) NOT NULL, PAROLA varchar(50) NOT NULL, HESAP_TURU varchar(50) NOT NULL, HESAP_ACMA_TARIHI date NOT NULL, KILITLI bit NOT NULL, PARA_MIKTARI double, PRIMARY KEY (HESAP_NUMARASI)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO hesap (HESAP_NUMARASI, TC, AD_SOYAD, PAROLA, HESAP_TURU, HESAP_ACMA_TARIHI, KILITLI, PARA_MIKTARI) VALUES (3, '34123064567', 'Ali Veli', '1234', 'Uzun Vadeli', '2017-06-12', false, 1461.0);
INSERT INTO hesap (HESAP_NUMARASI, TC, AD_SOYAD, PAROLA, HESAP_TURU, HESAP_ACMA_TARIHI, KILITLI, PARA_MIKTARI) VALUES (4, '56612345412', 'Olcay ?AHAN', '1234', 'Kisa Vadeli', '2017-05-13', false, 1000.0);
INSERT INTO hesap (HESAP_NUMARASI, TC, AD_SOYAD, PAROLA, HESAP_TURU, HESAP_ACMA_TARIHI, KILITLI, PARA_MIKTARI) VALUES (5, '87690876567', 'Yusuf Yaz?c?', '1234', 'Vadesiz', '2017-06-13', false, 8100.0);
INSERT INTO hesap (HESAP_NUMARASI, TC, AD_SOYAD, PAROLA, HESAP_TURU, HESAP_ACMA_TARIHI, KILITLI, PARA_MIKTARI) VALUES (6, '98738129301', 'Dusco TOSIC', '1234', 'Cari', '2017-06-13', false, 8752.0);

CREATE TABLE hesap_hareketleri (ID int NOT NULL AUTO_INCREMENT, HESAP_NUMARASI int NOT NULL, TARIH date NOT NULL, YATIRILAN_CEKILEN_MIKTAR int NOT NULL, FIRMA varchar(150), PRIMARY KEY (ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (1, 3, '2017-06-13', 100, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (2, 3, '2017-06-13', 150, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (3, 3, '2017-06-13', 100, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (4, 3, '2017-06-13', 11, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (5, 3, '2017-06-13', 100, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (6, 3, '2017-06-13', 11, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (7, 3, '2017-06-13', -11, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (8, 4, '2017-06-13', -4000, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (9, 5, '2017-06-13', 100, null);
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (10, 6, '2017-06-13', 852, 'Gül Tekstil');
INSERT INTO hesap_hareketleri (ID, HESAP_NUMARASI, TARIH, YATIRILAN_CEKILEN_MIKTAR, FIRMA) VALUES (11, 6, '2017-06-13', -100, 'Makro Sanayii');

